import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rick and Morty with Next.js",
  description: "Generated by OK",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={"flex flex-col h-screen justify-between"}
      >
        <Navbar />
        <div className="flex flex-col items-center">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
